name: Issue Report
description: Report a problem, request a feature, ask a question, or get general help with an issue.
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this report.
- type: textarea
  id: description
  attributes:
    label: Description
    description: What is this issue about? The more detailed you can be, the better! You can describe what you tried and what you expected to happen. You can also upload any screenshots or images here to help explain the issue (but please do not upload images of the mascot).
    placeholder: Describe the issue
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: URL
    description: If applicable, could you provide an example URL that relates to the issue? However, please do not post NSFW (Not Safe For Work) URLs. You may enter "N/A" if not applicable.
    placeholder: "Example: https://www.example.com/this/specific/url.html"
  validations:
    required: true
- type: input
  id: version
  attributes:
    label: Version
    description: What version of the app are you using? Please enter an actual number (do not enter "Latest" or "Current").
    placeholder: "Example: 1"
  validations:
    required: true
- type: input
  id: browser
  attributes:
    label: Browser
    description: What browser and browser version are you using? Please enter an actual number (do not enter "Latest" or "Current").
    placeholder: "Example: Chrome 100"
  validations:
    required: true
- type: input
  id: os
  attributes:
    label: OS
    description: What operating system are you using?
    placeholder: "Example: Windows 10"
  validations:
    required: true
- type: dropdown
  id: device
  attributes:
    label: Device
    description: What type of device are you using?
    options:
      - 
      - PC
      - Phone
      - Other
  validations:
    required: true
- type: checkboxes
  id: adherence
  attributes:
    label: Adherence
    description: Please confirm that you've read the [Sticky](https://github.com/sixcious/infy-scroll/issues/100) before posting your issue or question.
    options:
      - label: I have read the [Sticky](https://github.com/sixcious/infy-scroll/issues/100)
        required: true
  validations:
    required: true
