name: Problem Report
description: Report a problem
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out this report.
- type: textarea
  id: problem
  attributes:
    label: Problem
    description: What is the problem or issue? You can describe what you tried and what you expected to happen. You can upload any screenshots here to help explain the problem (but please do not upload images of the mascot).
    placeholder: Describe the problem
  validations:
    required: true
- type: input
  id: url
  attributes:
    label: URL
    description: If possible, could you provide an example URL of where the problem is happening? (However, please do not post NSFW URLs.)
    placeholder: "Example: https://www.example.com/right-here"
- type: input
  id: version
  attributes:
    label: Version
    description: What version are you using?
    placeholder: "Example: 0.8"
- type: input
  id: browser
  attributes:
    label: Browser
    description: What browser and browser version are you using?
    placeholder: "Example: Chrome 100"
- type: input
  id: os
  attributes:
    label: OS
    description: What operating system are you using?
    placeholder: "Example: Windows 10"
- type: dropdown
  id: device
  attributes:
    label: Device
    description: What type of device are you using?
    options:
      - PC
      - Phone
      - Other
